### ISSUE TITLE
Can't compile, using bindgen

### ISSUE THREAD

**Issue by 4silvertooth** [vsrs/rsciter#1]
Hi,
This is a really neat project,

but I am not able to run bindgen, specially generate.ps1, how were the bindings generated? Was LLVM used or mingw?

**Comment by vsrs** [comment]
@4silvertooth ,

Actually, you do not need to run bindgen yourself. Pregenerated code is included ([crates/rsciter/src/bindings](https://github.com/vsrs/rsciter/tree/master/crates/rsciter/src/bindings)).

Anyway, I've used LLVM on Windows to generate bindings, generate.ps1 should be in the Sciter SDK include folder.

Perhaps, it might not work with the latest SDK, as Andrew added GLX support and changed SDK (https://sciter.com/sciter-glx-goes-mainstream/), I did not test it yet.

**Comment by vsrs** [comment]
Starting from `v0.0.10` you can use `codegen` feature to generate bingings at build.

However, it's not recommended.

**Comment by LaineZ** [comment]
Hello there. Today, I wanted to try updating the bindings for the latest version of `sciter`. But encountered a weird bindgen issue, bindgen is screwing up `som_passport_t` struct from `sciter-om-def.h`, thus produces a compile error, because SOM system in the library relies on this struct.

```
error[E0560]: struct `generated::som_passport_t` has no field named `flags`
  --> crates\rsciter\src\bindings.rs:22:13
   |
22 |             flags: 0,
   |             ^^^^^ `generated::som_passport_t` does not have this field
   |
   = note: available fields are: `_address`

error[E0560]: struct `generated::som_passport_t` has no field named `name`
  --> crates\rsciter\src\bindings.rs:23:13
   |
23 |             name: crate::som::Atom::new(name)?.into(),
   |             ^^^^ `generated::som_passport_t` does not have this field
   |
   = note: available fields are: `_address`

and so on
```

from this
```c
typedef struct som_passport_t {
  UINT64             flags;
  som_atom_t         name;         // class name
  const som_property_def_t* properties; size_t n_properties; // virtual property thunks
  const som_method_def_t*   methods; size_t n_methods;       // method thunks
  som_item_getter_t  item_getter;  // var item_val = thing[k];
  som_item_setter_t  item_setter;  // thing[k] = item_val;
  som_item_next_t    item_next;    // for(var item of thisThing)
  // any property "inteceptors"
  som_any_prop_getter_t  prop_getter;  // var prop_val = thing.k;
  som_any_prop_setter_t  prop_setter;  // thing.k = prop_val;
  som_name_resolver_t name_resolver;
  void* reserved;
} som_passport_t;
```
bindgen generates only this:

```
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct som_passport_t {
    pub _address: u8,
}
```

I'm not proficient in bindgen or C programming. so don't beat me with slippers 🥰
