### ISSUE TITLE
Support statically linking

### ISSUE THREAD

**Issue by enp6** [vsrs/rsciter#2]
I have a commercial license for Sciter and have compiled it into a static library with static linking. I see that static linking is currently not supported, is that correct?

**Comment by enp6** [comment]
I tried static linking, but encountered these errors.

      librsciter-2a53e0b7bb867af4.rlib(rsciter-2a53e0b7bb867af4.rsciter.69c46a1a57aa6fc5-cgu.05.rcgu.o) : error LNK2001: unresolved external symbol _SciterAPI
      librsciter-2a53e0b7bb867af4.rlib(rsciter-2a53e0b7bb867af4.rsciter.69c46a1a57aa6fc5-cgu.04.rcgu.o) : error LNK2001: unresolved external symbol _SciterAPI
      librsciter-2a53e0b7bb867af4.rlib(rsciter-2a53e0b7bb867af4.rsciter.69c46a1a57aa6fc5-cgu.09.rcgu.o) : error LNK2001: unresolved external symbol _SciterAPI
      librsciter-2a53e0b7bb867af4.rlib(rsciter-2a53e0b7bb867af4.rsciter.69c46a1a57aa6fc5-cgu.08.rcgu.o) : error LNK2001: unresolved external symbol _SciterAPI
      librsciter-2a53e0b7bb867af4.rlib(rsciter-2a53e0b7bb867af4.rsciter.69c46a1a57aa6fc5-cgu.01.rcgu.o) : error LNK2001: unresolved external symbol _SciterAPI
      librsciter-2a53e0b7bb867af4.rlib(rsciter-2a53e0b7bb867af4.rsciter.69c46a1a57aa6fc5-cgu.07.rcgu.o) : error LNK2001: unresolved external symbol _SciterAPI
      librsciter-2a53e0b7bb867af4.rlib(rsciter-2a53e0b7bb867af4.rsciter.69c46a1a57aa6fc5-cgu.00.rcgu.o) : error LNK2001: unresolved external symbol _SciterAPI
      librsciter-2a53e0b7bb867af4.rlib(rsciter-2a53e0b7bb867af4.rsciter.69c46a1a57aa6fc5-cgu.06.rcgu.o) : error LNK2001: unresolved external symbol _SciterAPI

**Comment by vsrs** [comment]
@enp6 you need to specify where to look for the static sciter library (sciter-static-release.lib), for example using `.cargo/config.toml`:

```
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-L", "C:\\Projects\\3rd\\sciter\\private_sources\\stable\\lib\\windows\\x64",
    "-l", "sciter-static-release",
]
```

**Comment by enp6** [comment]
@vsrs I have already specified it and found the sciter static library I compiled, but I don't know if there is a problem with my static library compilation or what. Is there any option that needs to be modified for compiling the official source code of sciter?

**Comment by enp6** [comment]
@vsrs I ran generate-projects-windows-js.bat and then executed sciter.static.sln in build.js\windows. After disabling whole program optimization and compiling into a library, I still get the same error when calling the static library...

**Comment by enp6** [comment]
@vsrs Hello, have you tested static linking? I've been trying to modify it for the past few days without success. In the end, I tested a library (https://github.com/gaoqiangz/rust-sciter) that supports it, but it doesn't support the latest Rust. Would you like to take a look at how they implemented it for reference?

**Comment by vsrs** [comment]
@enp6

I've just checked the latest sciter sources (Updated to revision 11214.) with rustc 1.77.1 (7cf61ebde 2024-03-27), no problems.

You do not need to run `generate-projects-windows-js.bat`, just open `sciter.static.sln` and build `sciter.static` project (Release, x64) without changing any settings.

I use static linking from the very beginning, so yes, I've tested it a lot :) Linking to native C++ libraries might be tricky in rust sometimes, but it works.

Here is my full production `.cargo/config.toml`:

```
[target.x86_64-pc-windows-msvc]
rustflags = [
    # "-Zlocation-detail=none",
    "-C", "link-arg=/PDBALTPATH:%_PDB%", # remove full path in release builds
    "-C", "target-feature=+crt-static",
    "-L", "C:\\Projects\\3rd\\sciter\\private_sources\\stable\\lib\\windows\\x64",
    "-l", "Comdlg32",
    "-l", "windowscodecs",
    "-l", "Wininet",
    "-l", "gdi32",
    "-l", "Winspool",
    "-l", "sciter-static-release",

    "-C", "link-args=/alternatename:open=_open",
    "-C", "link-args=/alternatename:close=_close",
    "-C", "link-args=/alternatename:umask=_umask",
    "-C", "link-args=/alternatename:wcsrev=_wcsrev",
    "-C", "link-args=/alternatename:wcsdup=_wcsdup",
    "-C", "link-args=/alternatename:strdup=_strdup",    
    "-C", "link-args=/alternatename:unlink=_unlink",
    "-C", "link-args=/alternatename:fdopen=_fdopen",
    "-C", "link-args=/alternatename:fileno=_fileno",
    "-C", "link-args=/alternatename:isatty=_isatty",
    "-C", "link-args=/alternatename:lseek=_lseek",
    "-C", "link-args=/alternatename:read=_read",
    "-C", "link-args=/alternatename:write=_write",
    "-C", "link-args=/alternatename:rmdir=_rmdir",
    "-C", "link-args=/alternatename:getcwd=_getcwd",
    "-C", "link-args=/alternatename:chdir=_chdir",
    "-C", "link-args=/alternatename:mkdir=_mkdir",
]
```
Please make sure it applies

**Comment by enp6** [comment]
@vsrs If I build the static library using sciter.static.sln, the file size reaches 2GB. Do I need to disable whole program optimization?

**Comment by vsrs** [comment]
@enp6 It's absolutely fine, I also have sciter-static-release.lib about 2.5 GiB. After linking, the resulting rust binary will get additionally only about 8 MiB.  

P.S. I suggest to add this settings to Cargo.toml:

```
[profile.release]
strip = true      # strip symbols
debug = true      # generate pdb
lto = true        # Enable link-time optimization
codegen-units = 1 # Reduce number of codegen units to increase optimizations
panic = "abort"
```

**Comment by enp6** [comment]
@vsrs Hello, are you still using the email address listed on your GitHub profile? I sent you an email, please check it if it's convenient for you.

**Comment by vsrs** [comment]
@enp6 got the email, answered.

**Comment by enp6** [comment]
@vsrs Thank you very much!! The issue has been resolved, and the configuration you provided works perfectly!!
